// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Editor: typeof import('./components/Editor.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Resume: typeof import('./components/Resume.vue')['default']
    SocialLinks: typeof import('./components/SocialLinks.vue')['default']
  }
}
